web2com: !include ochsner_web2com.yaml
template: !include ochsner_web2com_template.yaml

# required:
# https://github.com/jcwillox/hass-template-climate/
climate:
  - platform: climate_template
    name: RaumtemperaturSollwert
    modes:
      - "auto"
    min_temp: 15
    max_temp: 30
    temp_step: 0.5
    current_temperature_template: "{{states('sensor.Normal_Raumtemperatur_Heizbetrieb') }}"
    set_temperature:
      - service: web2com.heating
        data:
          temperature:  "{{ temperature }}"
