heating:
  fields:
    temperature:
      name: NormalSetpointRoomTemperature
      description: New target temperature for room.
      example: 21.0
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "°C"
